import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testportcheck.uatemodal.com');
  await page.waitForURL('https://pe1id.uatemodal.com/Account/Login?**');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('pravuri');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('EltL3l5myjmxACh2yEYL$%-+');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  const response = await page.goto('https://ray.run');
  console.log(response.request().redirectedFrom()?.url()); 
await page.waitForURL('**.uatemodal.com/**');  
await page.waitForLoadState('networkidle');
//await page.waitForURL('https://dtr.uatemodal.com/TruckManagement');
  await page.getByRole('button').filter({ hasText: 'menu' }).click();
  await page.getByText('EMODAL COMMUNITY PORTAL', { exact: true }).click();
  await page.getByRole('link', { name: 'CONTAINERS' }).click();
  await page.getByRole('button', { name: 'Add to My Containers' }).click();
  await page.locator('#mat-chip-list-input-0').click();
  await page.locator('#mat-chip-list-input-0').fill('TRPK8061711');
  await page.getByRole('button', { name: 'SUBMIT' }).click();
  await page.locator('#searchres').click();
  await page.getByRole('button').filter({ hasText: /^filter_alt$/ }).click();
  await page.getByRole('textbox', { name: 'Container #' }).click();
  await page.getByRole('textbox', { name: 'Container #' }).fill('TRPK8061711');
  await page.getByRole('button', { name: 'APPLY' }).click();
  await page.getByText('keyboard_arrow_right').click();
  await page.getByRole('cell', { name: 'UNLOAD FROM VESSEL' }).locator('span').click();
  await page.getByText('more_vert').click();
  await page.getByRole('menuitem', { name: 'Add Pregate' }).click();
  await page.waitForURL('**.uatemodal.com/**');
  //await page.goto('https://termops.uatemodal.com/trucker/web/addvisit?watchlist=W3siZmFjaWxpdHlfY2QiOiJUUlBPQUsiLCJtb3ZldHlwZSI6IklQIiwidW5pdGNhdF9jZCI6IkNUUiIsInVuaXRfbmJyIjoiVFJQSzgwNjE3MTEiLCJyZWZ0eXBlIjoiIiwicmVmX25iciI6IiIsInNoaXBwaW5nbGluZV9jZCI6IkNNRFUiLCJ0cmFkZXR5cGVfY2QiOiJJIiwiZHJheXVuaXRfdWlkIjoiMjg1NzBjNmYtZDEzOS00OTY4LWJhNmQtYjhmNjVjNTcxNTI3IiwiYm9va2luZ191aWQiOiIiLCJncm91cGNvZGVfdWlkIjoiIiwibW92ZWNhdF9jZCI6IkFQUE9JTlRNRU5UIiwiYmFja3VybCI6Imh0dHBzOi8vdGVzdHBvcnRjaGVjay51YXRlbW9kYWwuY29tL2NvbnRhaW5lcnMifV0%3D&source=containers');
  await page.locator('#root').click();
  await page.getByRole('button').filter({ hasText: 'menu' }).click();
  await page.getByText('EMODAL COMMUNITY PORTAL', { exact: true }).click();
  await page.getByRole('link', { name: 'BOOKINGS' }).click();
  await page.getByRole('button', { name: 'Add Bookings' }).click();
  await page.getByRole('textbox', { name: 'Enter Booking No(s)' }).click();
  await page.getByRole('textbox', { name: 'Enter Booking No(s)' }).fill('TEST1234566');
  await page.getByRole('button', { name: 'SUBMIT' }).click();
  await page.getByText('info').first().click();
  await page.getByText('info').first().click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Number' }).click();
  await page.getByText('Booking# Line No records').click();
  await page.getByText('INACTIVE').click();
  await page.getByText('report').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('VIEW FEES').click();
  const page1 = await page1Promise;
  await page.getByLabel('close').click();
  await page.locator('#mat-checkbox-2 > .mat-checkbox-layout > .mat-checkbox-inner-container').click();
  await page.getByRole('button').filter({ hasText: 'email' }).click();
  await page.getByRole('button', { name: 'CANCEL' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('.mat-focus-indicator.button-group-btn.button-border-radius-right').first().click();
  const download = await downloadPromise;
  await page.locator('#searchres').click();
  await page.getByRole('button').filter({ hasText: 'menu' }).click();
  await page.getByText('EMODAL COMMUNITY PORTAL').click();
  await page.getByRole('link', { name: 'GROUP CODES' }).click();
  await page.getByRole('button', { name: 'Add Group Codes' }).click();
  await page.locator('div').filter({ hasText: /^Enter Group Code\(s\)$/ }).nth(4).click();
  await page.getByRole('textbox', { name: 'Enter Group Code(s)' }).fill('COFR');
  await page.getByRole('textbox', { name: 'Enter Group Code(s)' }).click();
  await page.getByRole('textbox', { name: 'Enter Group Code(s)' }).fill('RMTX');
  await page.getByRole('textbox', { name: 'Enter Group Code(s)' }).click();
  await page.getByRole('textbox', { name: 'Enter Group Code(s)' }).fill('csx');
  await page.getByRole('button', { name: 'SUBMIT' }).click();
  await page.getByRole('button').filter({ hasText: 'person' }).click();
  await page.getByRole('menuitem', { name: 'Log Out' }).click();
});