import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="username"]').press('Tab');
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="login-button"]').click();
  await page.getByRole('button', { name: 'Open Menu' }).click();
  await page.locator('[data-test="inventory-sidebar-link"]').click();
  await page.locator('[data-test="inventory-sidebar-link"]').click();
  await page.locator('[data-test="about-sidebar-link"]').click();
  await page.getByRole('link', { name: 'Saucelabs' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Sign in' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'User Name' }).fill('standard_user');
  await page1.getByRole('textbox', { name: 'User Name' }).press('Tab');
  await page1.getByRole('textbox', { name: 'Password' }).fill('secret_sauce');
  await page1.getByRole('button', { name: 'Log in' }).click();
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.locator('[data-test="primary-header"] div').filter({ hasText: 'Swag Labs' }).first().click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').fill('Hello');
  await page.locator('[data-test="firstName"]').press('Tab');
  await page.locator('[data-test="lastName"]').fill('How');
  await page.locator('[data-test="lastName"]').press('Tab');
  await page.locator('[data-test="postalCode"]').fill('11551155');
  await page.locator('[data-test="firstName"]').click();
  await page.locator('[data-test="firstName"]').press('Shift+Home');
  await page.locator('[data-test="firstName"]').fill('First');
  await page.locator('[data-test="firstName"]').press('Tab');
  await page.locator('[data-test="lastName"]').fill('LastName');
  await page.locator('[data-test="lastName"]').press('Shift+Tab');
  await page.locator('[data-test="firstName"]').press('End');
  await page.locator('[data-test="firstName"]').fill('FirstName');
  await page.locator('[data-test="continue"]').click();
  await page.locator('[data-test="finish"]').click();
  await page.locator('[data-test="back-to-products"]').click();
});